### ISSUE TITLE
能否新增直接网页端控制服务功能

### ISSUE THREAD

**Issue by lixiaolong2** [cshaptx4869/easyadmin#2]
执行命令 php crontab.php (windows) 或 php crontab.php start (linux)

这命令能否直接在网页触发，而不需要登录ssh进行触发？

**Comment by cshaptx4869** [comment]
> 执行命令 php crontab.php (windows) 或 php crontab.php start (linux)
> 
> 这命令能否直接在网页触发，而不需要登录ssh进行触发？

workerman 必须命令行启动的
